### PR TITLE
adding unit tests and fixing up setup.py

### PR DESCRIPTION
**Pull request by naegelejd**
This also fixes the issue of `pip uninstall ismrmrd` not "working".

### CODE REVIEW

**Comment by naegelejd** [comment]
The buildbot broke because I switched to use `setuptools.setup` instead of `distutils.core.setup`, which is the correct thing to do. This gives us better dependency management, the `test` and `nosetests` setup commands, and a working `pip uninstall`.
The problem is that `distutils` allows you to install to arbitrary paths, while `setuptools` is picky, hence the following error message from each buildslave:

```
running install
Checking .pth file support in ../local/share/gadgetron/python/
/usr/bin/python -E -c pass
TEST FAILED: ../local/share/gadgetron/python/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    ../local/share/gadgetron/python/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```

The best way to handle this would be to use a `virtualenv`, but a simpler (temporary?) solution would be to add `$GADGETRON_HOME/share/gadgetron/python` to `$PYTHONPATH` in the buildbot configuration. How does that sound?

**Comment by hansenms** [comment]
@naegelejd, whatever you think is the right solution.

Does this mean that I will have problems installing this in ~/local on my own machine too or is it just buildbot?

**Comment by naegelejd** [comment]
Ahh, I forgot to mention: I don't have this problem using the most recent version of `setuptools`. I haven't confirmed yet, but I believe just doing a `pip install -U setuptools` should ensure that you can install it wherever you like.

**Comment by hansenms** [comment]
OK, will you fix the buildmaster?

**Comment by naegelejd** [comment]
Yep done. Just waiting on the buildslaves to start rebuilding.

**Comment by hansenms** [comment]
They won't start on their own unless you restart the builds manually.

**Pull request merged**
