### PR TITLE
adding initial implementation of Meta container object

### PR DESCRIPTION
**Pull request by naegelejd**

### CODE REVIEW

**Comment by hansenms** [comment]
Looks great to me. I suppose it is trivial to do the "converter" on the cpp side in the Gadgetron, would you propose using the serialize and deserialize functions for that?

Please merge when ready, I am leaving it unmerged for now to give @inati a chance to comment.

**Comment by naegelejd** [comment]
The easiest thing to do would be to pass the xml string to python from C++
then the gadgets would have to call "deserialize" and vice versa. Doing a
conversion using Boost in the Gadgetron will be more difficult but it's
also a reasonable option.

**Comment by hansenms** [comment]
OK, it is just that there is a discrepancy between what is passed between the Gadgets in Python and CPP. So if you then in a Python gadget say self.put_next(imghead, data, meta) then the CPP part would get what? Where does it get serialized (in the Python Gadget base class?), or should the call be  self.put_next(imghead, data, meta.serialize()) and then deserialize on the CPP side? What do you think is best?

**Comment by naegelejd** [comment]
I think the best thing for Python gadgets is that they expect a `Meta`
object and `put_next` a `Meta` object. The C++ Python gadget could just
call `deserialize` and `serialize` before/after calling the Python gadget's
`process` method without involving any fancy Boost conversion.

**Pull request merged**
