### PR TITLE
Python3 fix for acquisition and image flags

### PR DESCRIPTION
**Pull request by inati**
@naegelejd could you please check this?

### CODE REVIEW

**Comment by naegelejd** [comment]
Looks good except the unit tests fail. Run `python setup.py test`. The bugs these commits fix would have been caught by the tests.

**Comment by inati** [comment]
Sorry, I had forgotten about that.  Now I'm stuck on the meta serialization.  StringIO stuff.  I made the following change to work around that, but now I'm stuck on the whole bytes vs strings.  

@@ -1,5 +1,9 @@
 import xml.etree.ElementTree as ET
-from io import StringIO
+
+try:
+    from StringIO import StringIO
+except ImportError:
+    from io import StringIO
 
 class Meta(dict):
     """A wrapper around a `dict` that allows for serialization and
@@ -22,7 +26,7 @@ class Meta(dict):
                 value = ET.SubElement(child, 'value')
                 value.text = str(v)
         # this is a 'workaround' to get ElementTree to generate the XML declaration
-        output = StringIO.StringIO()
+        output = StringIO()
         tree.write(output, encoding="UTF-8", xml_declaration=True)
         return output.getvalue()
 
I get this error:
======================================================================
ERROR: test_meta.test_serialize
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/souheil/src/ismrmrd-python/.eggs/nose-1.3.7-py3.4.egg/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/souheil/src/ismrmrd-python/tests/test_meta.py", line 51, in test_serialize
    xml = meta.serialize()
  File "/Users/souheil/src/ismrmrd-python/ismrmrd/meta.py", line 30, in serialize
    tree.write(output, encoding="UTF-8", xml_declaration=True)
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/xml/etree/ElementTree.py", line 778, in write
    short_empty_elements=short_empty_elements)
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/xml/etree/ElementTree.py", line 837, in _get_writer
    yield file.write
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/contextlib.py", line 336, in __exit__
    raise exc_details[1]
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/contextlib.py", line 321, in __exit__
    if cb(*exc_details):
  File "/Users/souheil/conda/envs/ismrmrd/lib/python3.4/contextlib.py", line 267, in _exit_wrapper
    callback(*args, **kwds)
TypeError: string argument expected, got 'bytes'

----------------------------------------------------------------------

**Comment by inati** [comment]
discussed offline with @naegelejd and made another commit.  Tests now pass on Python2 and Python3.

**Comment by naegelejd** [comment]
Sweet.

**Pull request merged**
