### PR TITLE
Update xsdata output format to dataclasses as pydata is deprecated

### PR DESCRIPTION
**Pull request by kspaceKelvin**
Update xsdata output format to address issue https://github.com/ismrmrd/ismrmrd-python/issues/40

### CODE REVIEW

**Comment by kspaceKelvin** [comment]
The "pydata" output type is deprecated in xsdata 21 and is changed to "dataclasses".  Class elements without an explicit ``minOccurs="0"`` are marked as mandatory, which means that ``(minimum, maximum, center)`` in ``limitType`` and ``(x, y, z)`` in ``matrixSizeType`` are now  mandatory.  Patch version is incremented and xsdata version is fixed to minimize future disruption.

@hansenms @kristofferknudsen, let me know if you have additional suggestions.

**Comment by hansenms** [comment]
@kristofferknudsen would you have a moment to look at this.

**Comment by kristofferknudsen** [comment]
Absolutely, I'm on it.

**Review by kristofferknudsen — APPROVED** [review]

**Comment by kristofferknudsen** [comment]
Looks good.

The now mandatory elements were effectively mandatory before, and I would consider not checking whether they were actually supplied to be a bug (fixed with this). 

I'm not generally a fan of freezing versions, but I guess XML Schema technology has slowed down somewhat since the start of the millennium. We should probably manually bump the version once in a while, to keep it from getting too ancient though.

**Comment by hansenms** [comment]
@kristofferknudsen do you have the ability to push to pypi?

**Comment by kspaceKelvin** [comment]
@kristofferknudsen I agree there are some downsides to fixing the version in case they make bugfixes and such, but I think the benefits of ensuring that we can deterministically build this repo even if there are upstream changes is worth it.  I'll keep an eye on if there are any xsdata updates in the future.

**Comment by kristofferknudsen** [comment]
@hansenms I do not have the rights to do that I think, but there should be a pipeline to handle that. I suspect it will trigger if you mark a new release. 

https://github.com/ismrmrd/ismrmrd-python/actions/workflows/python-publish.yml

**Pull request merged**
